### ISSUE TITLE
Write Mapping from USFM Headers to package.json fields

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#11]

**Comment by neutrinog** [comment]
@jag3773 this is what I have so far for the mapping.
https://github.com/neutrinog/Resource-Container/blob/87c6c04919c8fa8fb23edd597cda83812226231e/docs/usfm_manifest.rst

There's a list at the bottom of items I was not able to find appropriate tags for.

**Comment by jag3773** [comment]
That works for now.  We can circle back and add anything that may be missing later.

**Comment by neutrinog** [comment]
sure. this technically is not part of the spec anyway.
