### ISSUE TITLE
See if image zips for OBS follow new img container type

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#17]

**Comment by neutrinog** [comment]
@jag3773 we could add the images into a new repo in Door43-Catalog that is structured like a book. e.g. `en_obs_images-360px`, `en_obs_images-2160px`, etc.
In this way it would automatically be included in the catalog and the format would indicate they contain images.

**Comment by neutrinog** [comment]
* images will remain external links
* images will be on the cdn. How they get there we still don't know.

**Comment by neutrinog** [comment]
this is no longer relevant.
