### ISSUE TITLE
Process image links when converting into RC for API

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#18]

**Comment by neutrinog** [comment]
@jag3773 can you elaborate on this? I don't remember what the intent was.

**Comment by jag3773** [comment]
In Gogs most of our image links are going to be HTTP(s) resources, when we put these into the API we should convert the links to a format that links to the image RC.

**Comment by neutrinog** [comment]
This is no longer applicable per https://github.com/unfoldingWord-dev/Resource-Container/issues/17. Images will remain as external links.
