### ISSUE TITLE
Link to examples for each container type

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#19]
We need to link to pristine examples of what each container type looks like in Gogs.

- [ ] image
- [ ] audio
- [ ] video
- [x] book
- [x] help
- [x] dictionary
- [x] manual
- [x] bundle

**Comment by neutrinog** [comment]
This will be a `book` example https://git.door43.org/Door43/en-obs/pulls/8

**Comment by neutrinog** [comment]
Note: if we implement https://github.com/unfoldingWord-dev/Resource-Container/issues/42 we may deprecate the image audio and video container types.

@jag3773 after reviewing this I think we can safely deprecate the `image`, `audio`, and `video` container types now for a number of reasons.
1. we no longer need a container type to determine what format of content is provided. e.g. We either use the format field in the manifest or, if we follow through with https://github.com/unfoldingWord-dev/Resource-Container/issues/42, the file extension. This information is given it the catalog like `"format":"application/zip; type=audio content=audio/mp3 conformsto=rc0.2"`.
2. These types are already structured like the `book` type anyway.
3. If we follow through with #42 this would open up the possibility of providing media for any container type.

**Comment by jag3773** [comment]
@neutrinog Sounds good.

**Comment by neutrinog** [comment]
I removed the audio, video, and image types.
