### ISSUE TITLE
Link to code that parses RCs as a reference for other devs

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#20]

**Comment by neutrinog** [comment]
Working in an updated node library for managing RCs.
https://github.com/unfoldingWord-dev/node-resource-container/tree/rc0.2

**Comment by neutrinog** [comment]
Working on an updated android library https://github.com/unfoldingWord-dev/android-resource-container/tree/rc0.2

**Comment by neutrinog** [comment]
Having a python library built now. An issue for it is at https://github.com/neutrinog/Resource-Container/issues/2.

We can use this library later in https://github.com/unfoldingWord-dev/door43.org/issues/366 when we finish re-writing dokuwiki-to-rc script.
