### ISSUE TITLE
Update Resource Catalog Endpoint Example

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/Resource-Container#25]
This https://github.com/unfoldingWord-dev/door43.org/wiki/API-v3-Resource-Catalog-Endpoint needs to reflect the changes for 0.2.

**Comment by neutrinog** [comment]
@jag3773 how much of the manifest do you want in the api?

**Comment by neutrinog** [comment]
In updating the endpoint example I stipulated that a `format` array at the resource level would contain content for all projects within that resource while formats at the project level would only contain a single project.
