### ISSUE TITLE
remove redundancy from dict type and support new features

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/Resource-Container#41]
The config.yaml will store the following info:

* proper noun - Boolean to indicate if this is a proper noun.
* occurrences - An exhaustive list of occurrences of the word. These will be RC links.

The markdown file will contain the following:

* [x] Aliases (RC links)
* [x] Examples (RC links)
* [x] Bible links can have verse granularity.
* [ ] Strong's numbers

**Comment by neutrinog** [comment]
@jag3773 do we want to hash out the Strong's numbers now or add that later?

**Comment by jag3773** [comment]
See my comment in the PR.

**Comment by jag3773** [comment]
After double checking... maybe it would be better to do something like you see here: https://git.door43.org/Door43/en-ugl/src/master/content/G00425/01.md#word-data .  We could put the Proper Noun and Strongs data right in the file that way and leave the yaml file just for exhaustive occurrence information.

**Comment by neutrinog** [comment]
that could work.

**Comment by neutrinog** [comment]
note: the docs indicate we may add the strongs info to the markdown in the future. How that will look can be determined at a later time.
