### ISSUE TITLE
add rc url prefix to links

### ISSUE THREAD

**Issue by neutrinog** [unfoldingWord-dev/Resource-Container#43]
Make all the rc links use the form `rc://` so we can differentiate them from standard http urls.

**Comment by neutrinog** [comment]
We won't immediately use this but we will write up the spec.

**Comment by neutrinog** [comment]
blocked by #44

**Comment by neutrinog** [comment]
@jag3773  In writing this in I also want to switch the order of some items in the url.
Currently we have 

```markdown
[en-ulb](rc://en/ulb/gen/book)
```
but I'd like to have 
```markdown
[en-ulb](rc://en/ulb/book/gen)
```
note the switch of `gen` and `book`.
This makes a little more sense since a project is inside an RC type, which is inside a resource, etc.

It also makes more sense with our USFM bundles since since we could then use the first three parts of the uri (`en`, `ulb`, `book`) to address the RC instead of having to use parts 1, 2, and 4.

This would be the best time to make this chance since we can easily identify it with the new scheme.

**Comment by jag3773** [comment]
@neutrinog All sounds good.

**Comment by neutrinog** [comment]
I forgot to update all the examples to use the new key order in links.

**Comment by neutrinog** [comment]
ok these are all fixed now.
