### ISSUE TITLE
Resource containers in desktop does not seem to match the documentation

### ISSUE THREAD

**Issue by sea-liesch** [unfoldingWord-dev/Resource-Container#47]
Looking at http://resource-container.readthedocs.io/en/latest/index.html
I was expecting to see a manifest.ymal in the resource container found under the \library folder from translationStudio desktop v11.   Instead I see package.json.

Also, documentation states all extensions are supposed to be .ymal, but on the desktop, .yml is used.

**Comment by neutrinog** [comment]
tS does not support the latest Resource Container spec. It only supports [v0.1](http://resource-container.readthedocs.io/en/v0.1/).
Also, tS currently only uses RCs for the source content not the translations generated by the app.
